import Login from './Login'
import SignUp from './SignUp'
import Dashboard from './Dashboard'
import Splash from './Splash';
import ShowFullImg from './ShowfullImg';
import Chat from './Chat';
import Settings from './Settings';
import SenderVoiceCalling from './SenderVoiceCalling';
import RecevierVoiceCalling from './RecevierVoiceCalling';
import Search from './Search'
export{Login, SignUp, Dashboard, Splash,ShowFullImg,Chat,Settings,SenderVoiceCalling,RecevierVoiceCalling,Search};