require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'mobileChat' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'



  pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  target 'mobileChatTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'mobileChat-tvOS' do
  # Pods for mobileChat-tvOS

  target 'mobileChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
